// <auto-generated />
using HotelListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210404134948_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelListing.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uganda",
                            ShortName = "UG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kenya",
                            ShortName = "KE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rwanda",
                            ShortName = "RW"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ethiopia",
                            ShortName = "ETH"
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kampala",
                            CountryID = 1,
                            Name = "Sheraton",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nairobi",
                            CountryID = 2,
                            Name = "United Kenya Club",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kampala",
                            CountryID = 1,
                            Name = "Imperial Royal",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Nairobi",
                            CountryID = 2,
                            Name = "Six Eighty",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Addis",
                            CountryID = 4,
                            Name = "Washington",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 6,
                            Address = "Addis",
                            CountryID = 4,
                            Name = "Best Western",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Kigali",
                            CountryID = 3,
                            Name = "Okapi",
                            Rating = 3.0
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
